packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": "24.13.3"
  "@types/react": "19.2.18"
  "@types/react-dom": "19.2.5"
  "playwright-core": "1.62.1"
  "react": "19.2.8"
  "react-dom": "19.2.8"
  "typescript": "6.0.3"
  "vite": "8.2.2"
  "vitest": "4.1.10"

catalogMode: strict
cleanupUnusedCatalogs: true
linkWorkspacePackages: false
preferWorkspacePackages: false
