[package]
name = "plc-engineering-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
plc-commissioning = { path = "../plc-commissioning" }
plc-core = { path = "../plc-core" }
plc-observability = { path = "../plc-observability" }
plc-runtime = { path = "../plc-runtime" }
plc-system = { path = "../plc-system" }

[dev-dependencies]
plc-hardware = { path = "../plc-hardware" }

[lib]
crate-type = ["cdylib", "rlib"]

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
