//! Production verification replay over the integrated engineering session.
//!
//! This module deliberately interprets a small closed simulator-native ingress
//! language. A replay package cannot name a host path, invoke a shell, install
//! an artifact, open a transport, or request a deployable export.

use std::collections::{BTreeMap, VecDeque};
use std::fmt;

use plc_commissioning::PostLoadMode;
use plc_core::{ObjectId, Project};
use plc_observability::StableTargetId;
use plc_runtime::{Hash32, ReplayEvent, ReplayEventKind, Sha256};

use crate::{
    EngineeringSession, EngineeringSessionSnapshot, ReplayBoundaryHash, ReplayDecodeLimits,
    ReplayDivergence, ReplayPackage, ReplayPackageError, ReplayPackageEvent, ReplayPayloadValue,
    ReplayResultStatus, ReplayStateRegion, RestoreApproval, SystemCommandIdentity, SystemError,
};

/// Deterministic algorithm identity bound by the Phase 2 replay executor.
pub const ENGINEERING_REPLAY_ALGORITHM: &str = "XOSHIRO256SS-1";

/// Calculates the seven independently bound replay regions from an aggregate
/// snapshot. Capture and verification share this production implementation.
#[must_use]
pub fn engineering_replay_state_regions(
    snapshot: &EngineeringSessionSnapshot,
) -> BTreeMap<ReplayStateRegion, Hash32> {
    let runtime_regions = snapshot.runtime_state_region_hashes();
    let diagnostic_hash = aggregate_hash(
        b"PES-REPLAY-DIAGNOSTICS-1",
        &[
            snapshot.diagnostic_snapshot_hash,
            snapshot.runtime_bridge_hash,
            snapshot.hardware_diagnostic_bridge_hash,
        ],
    );
    BTreeMap::from([
        (ReplayStateRegion::Cpu, runtime_regions.cpu),
        (ReplayStateRegion::Memory, runtime_regions.memory),
        (ReplayStateRegion::Io, runtime_regions.io),
        (
            ReplayStateRegion::TimersCountersEdges,
            runtime_regions.timers_counters_edges,
        ),
        (ReplayStateRegion::Diagnostics, diagnostic_hash),
        (ReplayStateRegion::Forces, snapshot.force_snapshot_hash),
        (ReplayStateRegion::Trace, snapshot.trace_snapshot_hash),
    ])
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineeringReplayError {
    Package(ReplayPackageError),
    System(String),
    InitialSnapshotMismatch,
    ArtifactMismatch,
    ProfileMismatch,
    DeterminismMismatch,
    UnsupportedIngress {
        event_sequence: u64,
        kind: ReplayEventKind,
    },
    InvalidIngress {
        event_sequence: u64,
        field: &'static str,
    },
    MissingGeneratedEvent {
        event_sequence: u64,
    },
    RuntimeEventMismatch {
        event_sequence: u64,
    },
    MissingBoundary {
        event_sequence: u64,
    },
}

impl fmt::Display for EngineeringReplayError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Package(error) => write!(formatter, "invalid replay package: {error}"),
            Self::System(error) => write!(formatter, "engineering replay failed: {error}"),
            Self::InitialSnapshotMismatch => {
                formatter.write_str("replay package does not reference the supplied snapshot")
            }
            Self::ArtifactMismatch => {
                formatter.write_str("replay artifact does not match the restored runtime")
            }
            Self::ProfileMismatch => {
                formatter.write_str("replay profile does not match the restored runtime")
            }
            Self::DeterminismMismatch => {
                formatter.write_str("replay deterministic seed or algorithm does not match")
            }
            Self::UnsupportedIngress {
                event_sequence,
                kind,
            } => write!(
                formatter,
                "event {event_sequence} uses unsupported replay ingress {kind:?}"
            ),
            Self::InvalidIngress {
                event_sequence,
                field,
            } => write!(
                formatter,
                "event {event_sequence} has invalid closed ingress field {field}"
            ),
            Self::MissingGeneratedEvent { event_sequence } => write!(
                formatter,
                "event {event_sequence} was not generated by the reconstructed runtime"
            ),
            Self::RuntimeEventMismatch { event_sequence } => write!(
                formatter,
                "event {event_sequence} differs from the reconstructed runtime event"
            ),
            Self::MissingBoundary { event_sequence } => write!(
                formatter,
                "event {event_sequence} did not produce its required runtime boundary"
            ),
        }
    }
}

impl std::error::Error for EngineeringReplayError {}

impl From<ReplayPackageError> for EngineeringReplayError {
    fn from(value: ReplayPackageError) -> Self {
        Self::Package(value)
    }
}

impl From<SystemError> for EngineeringReplayError {
    fn from(value: SystemError) -> Self {
        Self::System(format!("{value:?}"))
    }
}

/// Result of executing a verification package from its referenced snapshot.
#[derive(Clone, Debug)]
pub struct EngineeringReplayExecution {
    pub divergence: Option<ReplayDivergence>,
    pub observed_boundaries: Vec<ReplayBoundaryHash>,
    pub final_snapshot: EngineeringSessionSnapshot,
}

#[derive(Clone, Debug)]
enum ClosedIngress {
    RequestRun,
    RequestStop,
    RawInput {
        identity: SystemCommandIdentity,
        target: StableTargetId,
        value: plc_runtime::CanonicalValue,
    },
    Scan(SystemCommandIdentity),
    Observation(SystemCommandIdentity),
    Passive,
}

/// Stateful production executor used by native Rust and the WASM bridge.
#[derive(Clone, Debug)]
pub struct EngineeringReplayExecutor {
    session: EngineeringSession,
    initial_snapshot_hash: Hash32,
    artifact_hash: Hash32,
    profile_hash: Hash32,
    deterministic_seed: u64,
    processed_events: Vec<ReplayPackageEvent>,
    generated_events: VecDeque<ReplayEvent>,
    observed_boundaries: Vec<ReplayBoundaryHash>,
}

impl EngineeringReplayExecutor {
    /// Reconstructs an engineering session and restores the complete aggregate
    /// snapshot through the same preview/approval/commit path as live use.
    pub fn from_snapshot(
        project: Project,
        controller_object_id: ObjectId,
        snapshot: &EngineeringSessionSnapshot,
    ) -> Result<Self, EngineeringReplayError> {
        let mut session = EngineeringSession::new(project, controller_object_id)?;
        session.build()?;
        session.power_on()?;
        let load = session.preview_load(PostLoadMode::Stop)?;
        session.commit_load(&load)?;
        session.go_online()?;
        let restore = session.preview_restore(snapshot)?;
        session.commit_restore(snapshot, &restore, RestoreApproval::approve(&restore))?;
        let profile_hash = session
            .read_model()?
            .profile_fingerprint
            .ok_or(EngineeringReplayError::ProfileMismatch)?;
        let deterministic_seed = {
            let read = session.read_model()?;
            session
                .universe()
                .controller(read.runtime_controller_id)
                .map(plc_commissioning::ControllerInstance::runtime)
                .ok_or_else(|| {
                    EngineeringReplayError::System(
                        "reconstructed runtime controller is unavailable".to_owned(),
                    )
                })?
                .deterministic_seed()
        };
        Ok(Self {
            session,
            initial_snapshot_hash: snapshot.content_hash,
            artifact_hash: snapshot.loaded_artifact_fingerprint,
            profile_hash,
            deterministic_seed,
            processed_events: Vec::new(),
            generated_events: VecDeque::new(),
            observed_boundaries: Vec::new(),
        })
    }

    /// Decodes and executes a canonical package using the shipped bounded
    /// decoder. This is the stable binary entry point used by `SystemBridge`.
    pub fn execute_bytes(
        project: Project,
        controller_object_id: ObjectId,
        snapshot: &EngineeringSessionSnapshot,
        bytes: &[u8],
    ) -> Result<EngineeringReplayExecution, EngineeringReplayError> {
        let package = ReplayPackage::decode(bytes, ReplayDecodeLimits::edu21())?;
        Self::execute(project, controller_object_id, snapshot, &package)
    }

    /// Executes every event in canonical order, reconstructs state, and
    /// compares newly calculated boundary/region hashes at the first boundary.
    pub fn execute(
        project: Project,
        controller_object_id: ObjectId,
        snapshot: &EngineeringSessionSnapshot,
        package: &ReplayPackage,
    ) -> Result<EngineeringReplayExecution, EngineeringReplayError> {
        let mut executor = Self::from_snapshot(project, controller_object_id, snapshot)?;
        let divergence = executor.verify_package(package)?;
        let final_snapshot = executor.session.capture_snapshot()?;
        Ok(EngineeringReplayExecution {
            divergence,
            observed_boundaries: executor.observed_boundaries,
            final_snapshot,
        })
    }

    /// Verifies one package on this freshly reconstructed executor. Ingress
    /// validation occurs before dispatch, allowing callers to prove rejected
    /// package shapes leave the reconstructed session untouched.
    pub fn verify_package(
        &mut self,
        package: &ReplayPackage,
    ) -> Result<Option<ReplayDivergence>, EngineeringReplayError> {
        if !self.processed_events.is_empty()
            || !self.generated_events.is_empty()
            || !self.observed_boundaries.is_empty()
        {
            return Err(EngineeringReplayError::System(
                "a replay executor can verify exactly one package".to_owned(),
            ));
        }
        if package.initial_snapshot_hash() != self.initial_snapshot_hash {
            return Err(EngineeringReplayError::InitialSnapshotMismatch);
        }
        if package.artifact_hash() != self.artifact_hash {
            return Err(EngineeringReplayError::ArtifactMismatch);
        }
        if package.profile_hash() != self.profile_hash {
            return Err(EngineeringReplayError::ProfileMismatch);
        }
        if package.deterministic_seed() != self.deterministic_seed
            || package.deterministic_algorithm() != ENGINEERING_REPLAY_ALGORITHM
        {
            return Err(EngineeringReplayError::DeterminismMismatch);
        }
        let mut apply_error = None;
        let divergence = package.verify_with(|event| {
            let causal = package
                .boundaries()
                .iter()
                .find(|boundary| {
                    boundary.segment == event.segment
                        && boundary.event_sequence == event.event_sequence
                })
                .map(|boundary| boundary.causal_input_event_sequence);
            match self.apply_event(event, causal) {
                Ok(boundary) => Ok(boundary),
                Err(error) => {
                    apply_error = Some(error);
                    Err(ReplayPackageError::InvalidEvent(
                        self.processed_events.len(),
                    ))
                }
            }
        });
        if let Some(error) = apply_error {
            return Err(error);
        }
        let divergence = divergence?;
        if !self.generated_events.is_empty() {
            return Err(EngineeringReplayError::MissingGeneratedEvent {
                event_sequence: package
                    .events()
                    .last()
                    .map_or(1, |event| event.event_sequence.saturating_add(1)),
            });
        }
        Ok(divergence)
    }

    /// Read-only access is useful to render the reconstructed state without
    /// giving package data a capability to mutate outside the interpreter.
    #[must_use]
    pub const fn session(&self) -> &EngineeringSession {
        &self.session
    }

    fn apply_event(
        &mut self,
        expected: &ReplayPackageEvent,
        causal_input_event_sequence: Option<u64>,
    ) -> Result<Option<ReplayBoundaryHash>, EngineeringReplayError> {
        if self.generated_events.is_empty() {
            let ingress = validate_closed_ingress(expected)?;
            let before = self.runtime()?.replay_events().len();
            match ingress {
                ClosedIngress::RequestRun => self.session.request_run()?,
                ClosedIngress::RequestStop => self.session.request_stop()?,
                ClosedIngress::RawInput {
                    identity,
                    target,
                    value,
                } => {
                    self.session
                        .set_raw_virtual_input(identity, target, value)?;
                }
                ClosedIngress::Scan(identity) | ClosedIngress::Observation(identity) => {
                    self.session.run_scan(identity)?;
                }
                ClosedIngress::Passive => {
                    return Err(EngineeringReplayError::MissingGeneratedEvent {
                        event_sequence: expected.event_sequence,
                    });
                }
            }
            let generated = self.runtime()?.replay_events()[before..].to_vec();
            self.generated_events.extend(generated);
        } else {
            validate_generated_event_shape(expected)?;
        }

        let actual = self.generated_events.pop_front().ok_or(
            EngineeringReplayError::MissingGeneratedEvent {
                event_sequence: expected.event_sequence,
            },
        )?;
        if !runtime_event_matches(expected, &actual) {
            return Err(EngineeringReplayError::RuntimeEventMismatch {
                event_sequence: expected.event_sequence,
            });
        }
        self.processed_events.push(expected.clone());

        if matches!(
            expected.kind,
            ReplayEventKind::ScanCompleted | ReplayEventKind::FatalFault
        ) {
            let causal_input_event_sequence =
                causal_input_event_sequence.ok_or(EngineeringReplayError::MissingBoundary {
                    event_sequence: expected.event_sequence,
                })?;
            let boundary = self.capture_boundary(expected, causal_input_event_sequence)?;
            self.observed_boundaries.push(boundary.clone());
            Ok(Some(boundary))
        } else {
            Ok(None)
        }
    }

    fn capture_boundary(
        &self,
        event: &ReplayPackageEvent,
        causal_input_event_sequence: u64,
    ) -> Result<ReplayBoundaryHash, EngineeringReplayError> {
        let runtime = self.runtime()?;
        let boundary = runtime
            .boundary_hashes()
            .iter()
            .rev()
            .find(|boundary| {
                (event.kind == ReplayEventKind::ScanCompleted && boundary.is_scan_end())
                    || (event.kind == ReplayEventKind::FatalFault && boundary.is_fatal_fault())
            })
            .ok_or(EngineeringReplayError::MissingBoundary {
                event_sequence: event.event_sequence,
            })?;
        let snapshot = self.session.capture_snapshot()?;
        let regions = engineering_replay_state_regions(&snapshot);
        ReplayBoundaryHash::from_runtime(
            boundary,
            event.event_sequence,
            causal_input_event_sequence,
            regions,
            &self.processed_events,
        )
        .map_err(Into::into)
    }

    fn runtime(&self) -> Result<&plc_runtime::VirtualController, EngineeringReplayError> {
        let read = self.session.read_model()?;
        self.session
            .universe()
            .controller(read.runtime_controller_id)
            .map(plc_commissioning::ControllerInstance::runtime)
            .ok_or_else(|| {
                EngineeringReplayError::System(
                    "reconstructed runtime controller is unavailable".to_owned(),
                )
            })
    }
}

fn validate_closed_ingress(
    event: &ReplayPackageEvent,
) -> Result<ClosedIngress, EngineeringReplayError> {
    if event.result.status != ReplayResultStatus::Accepted
        || event.payload.event_kind != event.kind
        || event.result.detail.event_kind != event.kind
        || !event.result.detail.fields.is_empty()
    {
        return Err(EngineeringReplayError::InvalidIngress {
            event_sequence: event.event_sequence,
            field: "result",
        });
    }
    let identity = SystemCommandIdentity {
        command_id: event.actor.command_id,
        idempotency_key: event.actor.idempotency_key,
        author_identity: event.actor.actor_id,
    };
    match event.kind {
        ReplayEventKind::RequestRun if event.payload.fields.is_empty() => {
            Ok(ClosedIngress::RequestRun)
        }
        ReplayEventKind::RequestStop if event.payload.fields.is_empty() => {
            Ok(ClosedIngress::RequestStop)
        }
        ReplayEventKind::ScanCompleted | ReplayEventKind::FatalFault
            if event.payload.fields.is_empty() =>
        {
            Ok(ClosedIngress::Scan(identity))
        }
        ReplayEventKind::HardwareBoundary if event.payload.fields.is_empty() => {
            Ok(ClosedIngress::Passive)
        }
        ReplayEventKind::ObservationBoundary if event.payload.fields.is_empty() => {
            Ok(ClosedIngress::Observation(identity))
        }
        ReplayEventKind::RawInputAccepted => {
            if event.payload.fields.len() != 2 {
                return Err(EngineeringReplayError::InvalidIngress {
                    event_sequence: event.event_sequence,
                    field: "raw-input-fields",
                });
            }
            let target = match event.payload.fields.get("target") {
                Some(ReplayPayloadValue::Identity(value)) => StableTargetId(*value),
                _ => {
                    return Err(EngineeringReplayError::InvalidIngress {
                        event_sequence: event.event_sequence,
                        field: "target",
                    });
                }
            };
            let value = match event.payload.fields.get("value") {
                Some(ReplayPayloadValue::Plc(value)) => value.to_runtime()?,
                _ => {
                    return Err(EngineeringReplayError::InvalidIngress {
                        event_sequence: event.event_sequence,
                        field: "value",
                    });
                }
            };
            Ok(ClosedIngress::RawInput {
                identity,
                target,
                value,
            })
        }
        ReplayEventKind::RequestRun
        | ReplayEventKind::RequestStop
        | ReplayEventKind::ScanCompleted
        | ReplayEventKind::FatalFault
        | ReplayEventKind::HardwareBoundary
        | ReplayEventKind::ObservationBoundary => Err(EngineeringReplayError::InvalidIngress {
            event_sequence: event.event_sequence,
            field: "payload",
        }),
        kind => Err(EngineeringReplayError::UnsupportedIngress {
            event_sequence: event.event_sequence,
            kind,
        }),
    }
}

fn validate_generated_event_shape(
    event: &ReplayPackageEvent,
) -> Result<(), EngineeringReplayError> {
    if event.result.status == ReplayResultStatus::Accepted
        && event.payload.event_kind == event.kind
        && event.result.detail.event_kind == event.kind
        && event.payload.fields.is_empty()
        && event.result.detail.fields.is_empty()
    {
        Ok(())
    } else {
        Err(EngineeringReplayError::InvalidIngress {
            event_sequence: event.event_sequence,
            field: "generated-event-shape",
        })
    }
}

fn runtime_event_matches(expected: &ReplayPackageEvent, actual: &ReplayEvent) -> bool {
    expected.segment == actual.segment
        && expected.kind == actual.kind
        && expected.event_sequence == actual.event_sequence
        && expected.virtual_timestamp_ms == actual.virtual_timestamp_ms
        && expected.runtime_payload_hash == actual.payload_hash
        && expected.runtime_result_hash == actual.result_hash
}

fn aggregate_hash(domain: &[u8], values: &[Hash32]) -> Hash32 {
    let mut bytes = Vec::with_capacity(domain.len() + values.len() * 32);
    bytes.extend_from_slice(domain);
    for value in values {
        bytes.extend_from_slice(value.as_bytes());
    }
    Sha256::digest(&bytes)
}
