import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { resolveInProject } from "./paths.mjs";

const wasmPath = resolveInProject(
  "target",
  "wasm32-unknown-unknown",
  "release",
  "foundation_wasm.wasm",
);
const generatedDirectory = resolveInProject(
  "apps",
  "foundation-shell",
  "src",
  "generated",
);
const generatedPath = path.join(generatedDirectory, "foundation-wasm.ts");

const wasm = await readFile(wasmPath);
if (
  wasm.byteLength < 8 ||
  !wasm.subarray(0, 8).equals(Buffer.from([0, 97, 115, 109, 1, 0, 0, 0]))
) {
  throw new Error("The compiled artifact is not a WebAssembly 1.0 module.");
}
if (wasm.byteLength > 128 * 1024) {
  throw new Error(`Foundation WASM exceeds 128 KiB: ${wasm.byteLength} bytes.`);
}

const module = new WebAssembly.Module(wasm);
const imports = WebAssembly.Module.imports(module);
if (imports.length !== 0) {
  throw new Error(`Foundation WASM must have zero imports: ${JSON.stringify(imports)}`);
}
const exportNames = new Set(WebAssembly.Module.exports(module).map(({ name }) => name));
for (const required of ["foundation_health", "foundation_health_len", "memory"]) {
  if (!exportNames.has(required)) {
    throw new Error(`Foundation WASM is missing export: ${required}`);
  }
}

const sha256 = createHash("sha256").update(wasm).digest("hex").toUpperCase();
const source = `// Generated by tools/foundation/embed-wasm.mjs. Do not edit.\n` +
  `export const FOUNDATION_WASM_SHA256 = ${JSON.stringify(sha256)} as const;\n` +
  `export const FOUNDATION_WASM_BASE64 = ${JSON.stringify(wasm.toString("base64"))} as const;\n`;

await mkdir(generatedDirectory, { recursive: true });
await writeFile(generatedPath, source, { encoding: "utf8", flag: "w" });
console.log(JSON.stringify({ bytes: wasm.byteLength, sha256 }));
